wandb_version: 1

architecture:
  desc: null
  value: CombinOptMTL
training_algortim:
  desc: null
  value: FAMO
dataset:
  desc: null
  value: ../../data/MRI_rois_20211114//MRI_rois_20211114.csv
target:
  desc: null
  value: modified
random state:
  desc: null
  value: 23
selected_diagnosis:
  desc: null
  value:
  - CN
  - AD
  - PD
  - LMCI
  - EMCI
  - MCI
  - FTD
selected_gender:
  desc: null
  value:
  - M
  - F
epochs:
  desc: null
  value: 500
learning_rate:
  desc: null
  value: 0.001
freeze_parametrs:
  desc: null
  value: Hybrid
optimizer:
  desc: null
  value: Adagrad
batch size:
  desc: null
  value: 256
scheduler:
  desc: null
  value: StepLR
weight_decay:
  desc: null
  value: 0.00025
gamma:
  desc: null
  value: 0.5
EarlyStopper_patience:
  desc: null
  value: 5
EarlyStopper_min_delta:
  desc: null
  value: 1
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1717251553
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.10.12
      5: 0.17.0
      8:
      - 5
      13: linux-x86_64
